### ISSUE TITLE
支持opentelemetry-java-instrumentation自带的Metrics

### ISSUE THREAD

**Issue by barrettzjh** [blueswen/spring-boot-observability#1]
你好，在opentelemetry-java-instrumentation中配置环境变量`OTEL_METRICS_EXPORTER=prometheus`时提供的metrics是否可以作为该metrics的数据源呢
link: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#prometheus-exporter

**Comment by blueswen** [comment]
可以。如 Open Telemetry 文件所述，你可以透過設定 System property `otel.metrics.exporter=prometheus` 或 Environment variable  `OTEL_METRICS_EXPORTER=prometheus` 讓你的服務增加一個 Prometheus metrics endpoint(預設為 0.0.0.0:9464)。配置完畢後你必須再修改 `etc/prometheus/prometheus.yml` 中 application job 的 metrics_path 與 target 去抓取 Open Telemetry Agent 統計的 metrics。

For those who don't understand Chinese:

Question: Can we use the metrics provided by Open Telemetry Agent's Prometheus Exporter to replace the metrics in Spring Boot Actuator and Micrometer?

Answer: Yes, it's possible. You can do this by setting the System property `otel.metrics.exporter=prometheus` or Environment variable `OTEL_METRICS_EXPORTER=prometheus`. This will open another server (default: 0.0.0.0:9464) to provide Prometheus metrics. Additionally, you need to update the metrics_path and target in `etc/prometheus/prometheus.yml` of your application job to retrieve the metrics from Open Telemetry Agent.

**Comment by barrettzjh** [comment]
那在grafana的panel中可以使用opentelemetry JVM metrics数据源吗
