### ISSUE TITLE
Unable to send logs to loki cloud

### ISSUE THREAD

**Issue by akshayr-mecha** [blueswen/spring-boot-observability#2]
Hello 
Thanks for this wonderful example
using this i am able to send traces to tempo cloud
but how are you sending logs to grafana loki?
Using this property only is not working
`logging.pattern.level=trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p`

**Comment by blueswen** [comment]
I use [Loki Docker Driver](https://grafana.com/docs/loki/latest/clients/docker-driver/) to push logs to local Loki. Check more details on [readme](https://github.com/blueswen/spring-boot-observability#loki---logs).

The property you mentioned is used to add trace ID to the log and has no relation with Loki. Spring Boot only writes log to the console.

**Comment by akshayr-mecha** [comment]
> I use [Loki Docker Driver](https://grafana.com/docs/loki/latest/clients/docker-driver/) to push logs to local Loki. Check more details on [readme](https://github.com/blueswen/spring-boot-observability#loki---logs).
> 
> The property you mentioned is used to add trace ID to the log and has no relation with Loki. Spring Boot application only writes log to the console.

Thanks for reply
got it
I want to push logs to grafana cloud directly what change i will have to do?

**Comment by akshayr-mecha** [comment]
Yes you are right, in opentelemetry grafana is not having push exporter. So i have to setup grafana agent.
Thanks for your reply.
