### ISSUE TITLE
Can this statistical time range be longer, such as one year？

### ISSUE THREAD

**Issue by oswardlx** [blueswen/spring-boot-observability#3]
Can this statistical time range be longer, such as one year？
<img width="282" alt="截屏2023-07-24 16 36 39" src="https://github.com/blueswen/spring-boot-observability/assets/33048303/f9c5c72b-8d2d-4290-be92-75bc99d04958">

**Comment by blueswen** [comment]
Hi @oswardlx ,

You can modify this panel's `relative time` in query options.

![relative_time](https://github.com/blueswen/spring-boot-observability/assets/1564148/8253fb2f-4158-44f0-a2b0-a41779c4a797)

**Comment by oswardlx** [comment]
thanks!  But there is another issue, when I increase the time range, the number of interface calls decreases
<img width="1130" alt="截屏2023-07-25 09 08 16" src="https://github.com/blueswen/spring-boot-observability/assets/33048303/fc74f2c6-1d61-46a7-82d6-5c669edcf480">
<img width="1111" alt="截屏2023-07-25 09 11 11" src="https://github.com/blueswen/spring-boot-observability/assets/33048303/c82ab291-a5de-47ee-b53a-2db547dc9dd1">

**Comment by blueswen** [comment]
Hi @oswardlx , sorry for the late reply.

There is another option `Max data points` when querying series. Prometheus will merge the data point, and the latest value shown on the panel will also be processed. You can modify the `Max data points` and run the query again, and you will find the value is changed. To get the actual latest value, you can query with the `Instant` type.

![Max data points and Instant type](https://github.com/blueswen/spring-boot-observability/assets/1564148/a1e70ed1-dd21-4a73-8ce0-c7a4eca1b66c)

**Comment by blueswen** [comment]
Hi @oswardlx,

After some research, I found a better way to display the latest value and sparkline simultaneously in the Stat panel. Need to query with `Both` type and use some transforms as follows. The updated dashboard is in the latest commit.

![Query](https://github.com/blueswen/spring-boot-observability/assets/1564148/cf9ba68e-c83b-45fb-8784-6123aacf0926)

![Transform](https://github.com/blueswen/spring-boot-observability/assets/1564148/538954e5-10f2-4794-9c4b-0117e14d3a97)

![Query](https://github.com/blueswen/spring-boot-observability/assets/1564148/33a1a85d-1dc0-4a19-a86d-c6168e6b03cb)

![Transform](https://github.com/blueswen/spring-boot-observability/assets/1564148/cbe09c5d-56c7-44c6-a8db-3ad08e83fbda)

Check more details on the reply I wrote on [Grafana Forum](https://community.grafana.com/t/display-both-a-sparkline-range-and-the-most-recent-value-instant-in-a-stat-panel/99758/2?u=blueswen).
